name: Despliegue Firebase
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Build and Deploy
        run: |
          npm install
          npm run build
          firebase deploy --only hosting
    env:
      CI: false
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

